class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(443, 368)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.txtCedula = QLineEdit(self.centralwidget)
        self.txtCedula.setObjectName(u"txtCedula")
        self.txtCedula.setGeometry(QRect(110, 120, 251, 31))
        self.btnLimpiar = QPushButton(self.centralwidget)
        self.btnLimpiar.setObjectName(u"btnLimpiar")
        self.btnLimpiar.setGeometry(QRect(240, 280, 81, 31))
        self.lblSexo = QLabel(self.centralwidget)
        self.lblSexo.setObjectName(u"lblSexo")
        self.lblSexo.setGeometry(QRect(30, 220, 71, 31))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.lblSexo.setFont(font)
        self.lblEmail = QLabel(self.centralwidget)
        self.lblEmail.setObjectName(u"lblEmail")
        self.lblEmail.setGeometry(QRect(30, 170, 71, 31))
        self.lblEmail.setFont(font)
        self.lblApellido = QLabel(self.centralwidget)
        self.lblApellido.setObjectName(u"lblApellido")
        self.lblApellido.setGeometry(QRect(30, 70, 71, 31))
        self.lblApellido.setFont(font)
        self.lblNombre = QLabel(self.centralwidget)
        self.lblNombre.setObjectName(u"lblNombre")
        self.lblNombre.setGeometry(QRect(30, 20, 71, 31))
        self.lblNombre.setFont(font)
        self.lblNombre.setMouseTracking(False)
        self.lblNombre.setTabletTracking(False)
        self.cmbSexo = QComboBox(self.centralwidget)
        self.cmbSexo.addItem("")
        self.cmbSexo.addItem("")
        self.cmbSexo.addItem("")
        self.cmbSexo.addItem("")
        self.cmbSexo.setObjectName(u"cmbSexo")
        self.cmbSexo.setGeometry(QRect(110, 220, 161, 31))
        self.txtEmail = QLineEdit(self.centralwidget)
        self.txtEmail.setObjectName(u"txtEmail")
        self.txtEmail.setGeometry(QRect(110, 170, 251, 31))
        self.txtNombre = QLineEdit(self.centralwidget)
        self.txtNombre.setObjectName(u"txtNombre")
        self.txtNombre.setGeometry(QRect(110, 20, 251, 31))
        self.btnGuardar = QPushButton(self.centralwidget)
        self.btnGuardar.setObjectName(u"btnGuardar")
        self.btnGuardar.setGeometry(QRect(110, 280, 81, 31))
        self.lblCedula = QLabel(self.centralwidget)
        self.lblCedula.setObjectName(u"lblCedula")
        self.lblCedula.setGeometry(QRect(30, 120, 71, 31))
        self.lblCedula.setFont(font)
        self.txtApellido = QLineEdit(self.centralwidget)
        self.txtApellido.setObjectName(u"txtApellido")
        self.txtApellido.setGeometry(QRect(110, 70, 251, 31))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 443, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.btnLimpiar.setText(QCoreApplication.translate("MainWindow", u"Limpiar", None))
        self.lblSexo.setText(QCoreApplication.translate("MainWindow", u"Sexo:", None))
        self.lblEmail.setText(QCoreApplication.translate("MainWindow", u"Email:", None))
        self.lblApellido.setText(QCoreApplication.translate("MainWindow", u"Apellido:", None))
        self.lblNombre.setText(QCoreApplication.translate("MainWindow", u"Nombre:", None))
        self.cmbSexo.setItemText(0, QCoreApplication.translate("MainWindow", u"Seleccionar ", None))
        self.cmbSexo.setItemText(1, QCoreApplication.translate("MainWindow", u"Masculino", None))
        self.cmbSexo.setItemText(2, QCoreApplication.translate("MainWindow", u"Femenino", None))
        self.cmbSexo.setItemText(3, QCoreApplication.translate("MainWindow", u"Prefiero no decirlo", None))

        self.btnGuardar.setText(QCoreApplication.translate("MainWindow", u"Guardar", None))
        self.lblCedula.setText(QCoreApplication.translate("MainWindow", u"Cedula:", None))
    # retranslateUi

